version: "3"

services:
  pg_data_base:
    container_name: "pg_data_base"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    image: "postgres:16.0"